apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sndq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sndq
    app.kubernetes.io/part-of: tkrw-pr712-0075-0021-app
  name: devfile-sample-sndq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sndq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sndq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-sndq@sha256:29fe2f777ccd7ddcfcea901ae4dece2956745517cdd091cfc8aae8be3d75e649
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
